apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test4argocdapp
  namespace: argocd
spec:
  project: default  
  destination:
    namespace: test4argocdapp  #update namespace name if you wish
    name: in-cluster  #update cluster name if its different
  source:
    repoURL: 'https://github.com/davidboukari/test4argocd.git/'  #replace with your username
    path: nginx
    path: nginx/charts/common
#    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml #any custom value file you want to apply.
